### ISSUE TITLE
About training command

### ISSUE THREAD

**Issue by jetitime** [cv516Buaa/ST-DASegNet#5]
Hello, author. Can you tell me the meaning of '2' in './tools/dist_train.sh ./experiments/deeplabv3/config/ST-DASegNet_deeplabv3plus_r50-d8_4x4_512x512_40k_Potsdam2Vaihingen.py 2' ? Thank you very much!

**Comment by cv516Buaa** [comment]
gpu number

**Comment by jetitime** [comment]
Thank you very much!!

**Comment by jetitime** [comment]
Hi, author! Sorry to trouble you again. Because the space left on my device was not enough, the training progress stopped after iter_35000. I want to test by using the iter_14000, so i input the command " ./tools/dist_test.sh ./experiments/segformerb5/config/ST-DASegNet_segformerb5_769x769_40k_Potsdam2Vaihingen.py 1 ./experiments/segformerb5/ST-DASegNet_results/iter_14000.pth --eval mIoU
" , but it said "launch.py: error: argument --nproc_per_node: invalid int value: './experiments/segformerb5/ST-DASegNet_results/iter_14000.pth'"

**Comment by jetitime** [comment]
Hi, author! Sorry to trouble you again. Because the space left on my device was not enough, the training progress stopped after 35000 iterations. I want to use the iter_10000.pth to test. 
However, when i input command "  ./tools/dist_test.sh ./experiments/segformerb5/config/ST-DASegNet_segformerb5_769x769_40k_Potsdam2Vaihingen.py 1 ./experiments/segformerb5/ST-DASegNet_results/iter_10000.pth --eval mIoU ", it said " launch.py: error: argument --nproc_per_node: invalid int value: './experiments/segformerb5/ST-DASegNet_results/iter_10000.pth' "

**Comment by jetitime** [comment]
Sorry to disturb you again! From the passage I learned how to realize  domain disentangled module, but I still puzzle about principle of feature disentangled. It's sad that I didn't find useful article about feature disentangled. Is there any recommended article? Thank you very much!

**Comment by cv516Buaa** [comment]
In our paper, we do not refer to any paper specifically designing domain disentangled module. we may not the first to propose the concept of domain disentangling in UDA segmentation direction, but ST-DASegNet still provides a new paradigm. When designing DDM, we refer to the attention mechanism of SENet and DANet. 
  Thanks for you Q.

**Comment by jetitime** [comment]
Thanks for your reply！I’ll learn about SENet and DANet.
